### ISSUE TITLE
How To Unit Test Anything (almost)

### ISSUE THREAD

**Issue by lukaszreszke** [ShortRuby/submit#96]
## Link to the content
https://youtu.be/oVY_AdVcoNE

## Anything else
In this video we explain how you can test complex cases by introducing an abstraction. We also discuss how that impacts your test suite and development speed.

**Comment by lucianghinda** [comment]
Thank you for the submission. It is a good content and I subscribed to your channel. I cannot include this in this week newsletter because ShortRuby is about what happened in the previous week and this video is from 3 weeks ago. 

But I added your channel to my RSS feeder and will watch closely when you publish something new or please submit it here in the week when you publish it.

**Comment by lukaszreszke** [comment]
Understood. Thank you @lucianghinda!
